from __future__ import annotations

import json
import os
import shutil
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape

from .model import Page, collect_pages, normalize_wiki_root
from .links import iter_markdown_links, resolve_markdown_link
import re
from .render import plain_text_from_markdown, render_markdown

SITE_MARKER = ".droid-wiki-site"


def html_output_path(out_dir: Path, page_path: str) -> Path:
    rel = Path(page_path)
    if rel.name == "index.md":
        return out_dir / rel.with_suffix(".html")
    return out_dir / rel.with_suffix(".html")


def page_url(page_path: str) -> str:
    rel = Path(page_path)
    url = rel.with_suffix(".html").as_posix()
    if url.endswith("/index.html"):
        return url[: -len("index.html")]
    return url


def relative_href(from_html: Path, target_html: Path) -> str:
    return Path(os.path.relpath(target_html, start=from_html.parent)).as_posix()


def page_href(from_html: Path, out_dir: Path, page_path: str) -> str:
    return relative_href(from_html, html_output_path(out_dir, page_path))


def build_sidebar(pages: list[Page], from_html: Path, out_dir: Path) -> list[dict[str, str]]:
    return [{"title": page.title, "url": page_href(from_html, out_dir, page.path), "id": page.id} for page in pages]


def asset_path(from_html: Path, out_dir: Path, asset: str) -> str:
    return relative_href(from_html, out_dir / "assets" / asset)


def prepare_output_dir(root: Path, out: Path) -> None:
    if out == root or root in out.parents or out in root.parents:
        raise ValueError(f"Site and wiki directories must not overlap: {out}")
    if out.exists():
        marker = out / SITE_MARKER
        if not out.is_dir() or not marker.is_file() or marker.is_symlink():
            raise ValueError(
                f"Refusing to replace unmarked output directory: {out}. "
                "Choose a new destination; a familiar directory name does not authorize replacement."
            )
        shutil.rmtree(out)
    (out / "assets").mkdir(parents=True)
    (out / SITE_MARKER).write_text("generated by droid-wiki-local\n", encoding="utf-8")


def build_site(wiki_dir: str | Path, out_dir: str | Path) -> dict[str, int]:
    root = normalize_wiki_root(wiki_dir)
    out = Path(out_dir).expanduser()
    if out.is_symlink():
        raise ValueError(f"Refusing symlink output: {out}")
    out = out.resolve()

    template_dir = Path(__file__).parent / "templates"
    env = Environment(
        loader=FileSystemLoader(template_dir),
        autoescape=select_autoescape(["html", "xml"]),
    )
    template = env.get_template("page.html")
    pages = collect_pages(root)
    if not pages:
        raise ValueError("No Markdown pages found")
    # Pre-render all source before replacing any previously generated output.
    rendered = {page.path: render_markdown(page.source_path.read_text(encoding="utf-8")) for page in pages}
    prepare_output_dir(root, out)

    shutil.copyfile(template_dir / "style.css", out / "assets" / "style.css")
    shutil.copyfile(template_dir / "search.js", out / "assets" / "search.js")

    search_entries: list[dict[str, str]] = []
    for index, page in enumerate(pages):
        markdown = page.source_path.read_text(encoding="utf-8")
        content_html = rendered[page.path]
        html_path = html_output_path(out, page.path)
        html_path.parent.mkdir(parents=True, exist_ok=True)
        sidebar = build_sidebar(pages, html_path, out)
        previous_page = pages[index - 1] if index > 0 else None
        next_page = pages[index + 1] if index + 1 < len(pages) else None
        html = template.render(
            title=page.title,
            content=content_html,
            sidebar=sidebar,
            current_id=page.id,
            home_url=relative_href(html_path, out / "index.html"),
            previous={"title": previous_page.title, "url": page_href(html_path, out, previous_page.path)}
            if previous_page
            else None,
            next={"title": next_page.title, "url": page_href(html_path, out, next_page.path)} if next_page else None,
            style_href=asset_path(html_path, out, "style.css"),
            search_href=asset_path(html_path, out, "search.js"),
            search_json=relative_href(html_path, out / "search.json"),
        )
        html_path.write_text(html, encoding="utf-8")
        search_entries.append(
            {
                "id": page.id,
                "title": page.title,
                "path": page.path,
                "url": page_url(page.path),
                "summary": page.summary,
                "text": plain_text_from_markdown(markdown),
            }
        )

    for page in pages:
        markdown = page.source_path.read_text(encoding="utf-8")
        attachments = [link for _, link in iter_markdown_links(markdown)]
        attachments.extend(re.findall(r"!\[[^\]]*\]\(([^)]+)\)", markdown))
        for link in attachments:
            target = resolve_markdown_link(page.source_path, link)
            if target is None or not target.is_file() or target.suffix == ".md":
                continue
            if not target.is_relative_to(root):
                continue
            destination = out / target.relative_to(root)
            if destination.exists():
                # Renderer-owned assets take precedence over source attachments.
                continue
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(target, destination)

    (out / "search.json").write_text(json.dumps(search_entries, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return {"pages": len(pages)}
